sudo: false
language: shell
script:
  - echo "No tests"
notifications:
  webhooks:
    - 'https://beekeeper.octoblu.com/webhooks/travis:ci'
after_success:
  - npm run coverage
  - 'npm run mocha:json'
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'bash <(curl -s https://codecov.octoblu.com/bash)'
